### ISSUE TITLE
Personnel

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/nutshell-star-destroyer#3]
# User Story
- [x] As a user, I should be able to view all Personnel. #15 
- [x]  As a user, I should be able to add Personnel. #16 
- [ ] As a user, I should be able to edit Personnel. #14 
- [ ] As a user, I should be able to remove Personnel. #13
