### ISSUE TITLE
Enemies

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/nutshell-star-destroyer#4]
# User Stories
- [x] As a user, I should be able to view all the Enemies. #23  
- [x] As a user, I should be able to add an Enemy. #22 
- [x] As a user, I should be able to edit an Enemy. #24 
- [x] As a user, I should be able to delete an Enemy. #25
