### ISSUE TITLE
Planetary Sectors

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/nutshell-star-destroyer#5]
# User Stories
- [ ] As a user, I should be able to view all the Planetary Sectors. #17 
- [ ] As a user, I should be able to add a Planetary Sector. #19
- [ ] As a user, I should be able to edit a Planetary Sector. #18
- [ ] As a user, I should be able to delete a Planetary Sector.#20
