### ISSUE TITLE
Weapons

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-10/nutshell-star-destroyer#6]
# User Stories
- [x] As a user, I should be able to view all active Weapons. #27 
- [x] As a user, I should be able to create a Weapon. #28 
- [ ] As a user, I should be able to edit a Weapon. #29 
- [x] As a user, I should be able to delete a Weapon. #30
